server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Pravas@93
  application:
    name: HOTEL-SERVICE
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

  eureka:
    #  instance:
    #    prefer-ip-address: true
    client:
      #    fetch-registry: true
      #    register-with-eureka: true
      service-url:
        default-zone: http://localhost:8761/eureka
