server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Pravas@93
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
#  instance:
#    prefer-ip-address: true
  client:
#    fetch-registry: true
#    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
